; Generated by Siren
; Source: ampharos.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Ampharos_Siren:
	channel_count 4
	channel 5, Cry_Ampharos_Siren_Ch5
	channel 6, Cry_Ampharos_Siren_Ch6
	channel 7, Cry_Ampharos_Siren_Ch7
	channel 8, Cry_Ampharos_Siren_Ch8

Cry_Ampharos_Siren_Ch5:
	duty_cycle_pattern 2, 2, 1, 1
	square_note 2, 14, 8, 1150
	square_note 2, 14, 8, 1328
	square_note 2, 14, 8, 1608
	square_note 2, 13, 8, 1430
	square_note 2, 14, 8, 1684
	square_note 2, 12, 8, 1577
	square_note 2, 13, 8, 1586
	square_note 2, 13, 8, 1778
	square_note 2, 13, 8, 1511
	square_note 2, 12, 8, 1710
	square_note 2, 12, 8, 1511
	square_note 2, 12, 8, 1405
	square_note 2, 11, 8, 1719
	square_note 2, 11, 8, 1707
	square_note 2, 10, 8, 228
	square_note 2, 7, 8, 1418
	square_note 2, 3, 8, 1393
	square_note 2, 1, 8, 1418
	square_note 1, 0, 8, 0
	sound_ret

Cry_Ampharos_Siren_Ch6:
	duty_cycle_pattern 0, 3, 0, 3
	square_note 2, 11, 8, 1652
	square_note 2, 11, 8, 1781
	square_note 2, 11, 8, 1779
	square_note 2, 11, 8, 1811
	square_note 2, 11, 8, 1825
	square_note 2, 10, 8, 1811
	square_note 2, 10, 8, 1753
	square_note 2, 10, 8, 1900
	square_note 2, 10, 8, 1705
	square_note 2, 10, 8, 1607
	square_note 2, 10, 8, 1727
	square_note 2, 10, 8, 1703
	square_note 2, 8, 8, 1829
	square_note 2, 8, 8, 1839
	square_note 2, 8, 8, 1703
	square_note 2, 5, 8, 1493
	square_note 2, 2, 8, 1749
	square_note 2, 1, 8, 1208
	square_note 1, 0, 8, 0
	sound_ret

Cry_Ampharos_Siren_Ch7:
	square_note 2, 2, 6, 1599
	square_note 2, 2, 5, 1688
	square_note 2, 2, 3, 1828
	square_note 2, 2, 3, 1739
	square_note 2, 2, 9, 1866
	square_note 2, 2, 4, 1813
	square_note 2, 2, 7, 1817
	square_note 2, 2, 6, 1913
	square_note 2, 2, 5, 1780
	square_note 2, 2, 2, 1879
	square_note 2, 2, 6, 1780
	square_note 2, 2, 7, 1727
	square_note 2, 2, 4, 1884
	square_note 2, 2, 9, 1878
	square_note 2, 2, 4, 1138
	square_note 2, 3, 2, 1733
	square_note 2, 3, 7, 1721
	square_note 2, 3, 5, 1733
	square_note 1, 0, 0, 0
	sound_ret

Cry_Ampharos_Siren_Ch8:
	noise_note 5, 13, 8, 92
	noise_note 5, 12, 8, 92
	noise_note 5, 13, 2, 92
	noise_note 5, 12, 5, 76
	noise_note 5, 12, 5, 92
	noise_note 5, 12, 8, 92
	noise_note 5, 12, 2, 92
	noise_note 5, 8, 1, 92
	noise_note 5, 4, 1, 92
	noise_note 1, 0, 8, 92
	sound_ret
