; Generated by Siren 2.0.0
; Source: blastoise.wav
; Effect: Auto · based on Vibrato
; Volume: 60%
; Fade In: No
; Fade Out: No
; Channels: 1, 2, 3, 4
; Pitch Level: 0
; Resonance Level: -33
; Weight Level: 4
; Intonation Level: 0
; Texture Level: 42
; Breathiness Level: -66
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Blastoise_Siren:
	channel_count 4
	channel 5, Cry_Blastoise_Siren_Ch5
	channel 6, Cry_Blastoise_Siren_Ch6
	channel 7, Cry_Blastoise_Siren_Ch7
	channel 8, Cry_Blastoise_Siren_Ch8

Cry_Blastoise_Siren_Ch5:
	square_note 0, 0, 8, 0
	duty_cycle 0
	square_note 0, 4, 8, 1410
	duty_cycle 3
	square_note 0, 8, 8, 1561
	duty_cycle 2
	square_note 0, 7, 8, 1218
	duty_cycle 0
	square_note 0, 8, 8, 1060
	duty_cycle 2
	square_note 0, 8, 8, 1504
	duty_cycle 0
	square_note 0, 9, 8, 1444
	duty_cycle 2
	square_note 0, 8, 8, 1208
	duty_cycle 3
	square_note 0, 8, 8, 1446
	duty_cycle 2
	square_note 0, 9, 8, 1196
	duty_cycle 0
	square_note 0, 9, 8, 1088
	duty_cycle 2
	square_note 0, 9, 8, 1760
	square_note 0, 9, 8, 1218
	square_note 0, 8, 8, 1240
	duty_cycle 1
	square_note 0, 9, 8, 1478
	duty_cycle 2
	square_note 0, 9, 8, 1760
	square_note 0, 9, 8, 1734
	square_note 0, 8, 8, 1748
	duty_cycle 0
	square_note 0, 8, 8, 1150
	square_note 0, 7, 8, 1322
	duty_cycle 2
	square_note 0, 8, 8, 1278
	duty_cycle 0
	square_note 0, 7, 8, 1266
	duty_cycle 2
	square_note 0, 8, 8, 1731
	square_note 0, 8, 8, 1752
	duty_cycle 0
	square_note 0, 8, 8, 1218
	duty_cycle 2
	square_note 0, 8, 8, 1778
	square_note 0, 7, 8, 1762
	square_note 0, 7, 8, 1206
	duty_cycle 3
	square_note 0, 7, 8, 1060
	duty_cycle 2
	square_note 0, 7, 8, 1928
	square_note 0, 8, 8, 1766
	square_note 0, 6, 8, 1306
	square_note 0, 7, 8, 1173
	duty_cycle 1
	square_note 0, 8, 8, 1238
	duty_cycle 2
	square_note 0, 7, 8, 1858
	square_note 0, 7, 8, 1772
	duty_cycle 0
	square_note 0, 7, 8, 1465
	duty_cycle 1
	square_note 0, 6, 8, 1788
	duty_cycle 2
	square_note 0, 7, 8, 1864
	square_note 0, 7, 8, 1782
	duty_cycle 0
	square_note 0, 8, 8, 856
	duty_cycle 1
	square_note 0, 7, 8, 1512
	duty_cycle 3
	square_note 0, 7, 8, 1764
	duty_cycle 2
	square_note 0, 7, 8, 1185
	duty_cycle 0
	square_note 0, 7, 8, 1306
	square_note 0, 6, 8, 1196
	duty_cycle 1
	square_note 0, 7, 8, 1244
	square_note 0, 7, 8, 1088
	duty_cycle 0
	square_note 0, 6, 8, 1504
	square_note 0, 5, 8, 1289
	square_note 0, 6, 8, 1541
	duty_cycle 2
	square_note 0, 5, 8, 1847
	square_note 0, 6, 8, 1567
	duty_cycle 3
	square_note 0, 5, 8, 1830
	duty_cycle 2
	square_note 0, 4, 8, 1802
	square_note 0, 5, 8, 1790
	square_note 0, 3, 8, 1852
	duty_cycle 1
	square_note 0, 3, 8, 1811
	duty_cycle 2
	square_note 0, 2, 8, 1792
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Blastoise_Siren_Ch6:
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 2, 8, 1777
	duty_cycle 0
	square_note 0, 5, 8, 1297
	duty_cycle 1
	square_note 0, 5, 8, 1026
	duty_cycle 2
	square_note 0, 5, 8, 1225
	duty_cycle 3
	square_note 0, 5, 8, 1304
	square_note 0, 6, 8, 1355
	duty_cycle 0
	square_note 0, 5, 8, 1002
	square_note 0, 5, 8, 1018
	duty_cycle 3
	square_note 0, 6, 8, 1326
	square_note 0, 7, 8, 1516
	duty_cycle 2
	square_note 0, 5, 8, 1605
	square_note 0, 5, 8, 1816
	square_note 0, 5, 8, 1832
	duty_cycle 3
	square_note 0, 5, 8, 1780
	duty_cycle 0
	square_note 0, 4, 8, 1689
	square_note 0, 5, 8, 1702
	duty_cycle 2
	square_note 0, 5, 8, 1826
	square_note 0, 6, 8, 1762
	duty_cycle 0
	square_note 0, 4, 8, 1784
	duty_cycle 3
	square_note 0, 5, 8, 1782
	duty_cycle 2
	square_note 0, 5, 8, 1727
	duty_cycle 1
	square_note 0, 6, 8, 1590
	duty_cycle 0
	square_note 0, 2, 8, 1605
	duty_cycle 2
	square_note 0, 5, 8, 1724
	square_note 0, 0, 8, 0
	square_note 0, 4, 8, 1564
	square_note 0, 4, 8, 1775
	duty_cycle 3
	square_note 0, 4, 8, 1817
	duty_cycle 1
	square_note 0, 4, 8, 1835
	duty_cycle 2
	square_note 0, 2, 8, 1854
	square_note 0, 0, 8, 0
	duty_cycle 3
	square_note 0, 2, 8, 1849
	square_note 0, 4, 8, 1827
	duty_cycle 1
	square_note 0, 4, 8, 1821
	duty_cycle 2
	square_note 0, 4, 8, 1853
	duty_cycle 1
	square_note 0, 5, 8, 1817
	duty_cycle 3
	square_note 0, 2, 8, 1835
	duty_cycle 2
	square_note 0, 5, 8, 1799
	duty_cycle 0
	square_note 0, 4, 8, 1696
	duty_cycle 2
	square_note 0, 6, 8, 1759
	square_note 0, 4, 8, 1764
	duty_cycle 1
	square_note 0, 2, 8, 1863
	duty_cycle 2
	square_note 0, 4, 8, 1820
	duty_cycle 3
	square_note 0, 4, 8, 1797
	duty_cycle 2
	square_note 0, 4, 8, 1770
	square_note 0, 2, 8, 1761
	square_note 0, 4, 8, 1857
	square_note 0, 4, 8, 1862
	square_note 0, 2, 8, 1854
	duty_cycle 1
	square_note 0, 2, 8, 1846
	duty_cycle 2
	square_note 0, 2, 8, 1880
	square_note 0, 2, 8, 1844
	duty_cycle 3
	square_note 0, 2, 8, 1745
	duty_cycle 2
	square_note 0, 2, 8, 1829
	square_note 0, 2, 8, 1830
	square_note 0, 2, 8, 1905
	square_note 0, 2, 8, 1859
	duty_cycle 3
	square_note 0, 1, 8, 1602
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Blastoise_Siren_Ch7:
	square_note 0, 0, 1, 1907
	square_note 0, 3, 1, 1729
	square_note 0, 3, 1, 1805
	square_note 0, 3, 1, 1632
	square_note 0, 3, 1, 1554
	square_note 0, 3, 1, 1775
	square_note 0, 3, 1, 1746
	square_note 0, 3, 1, 1628
	square_note 0, 3, 1, 1747
	square_note 0, 3, 1, 1622
	square_note 0, 3, 1, 1567
	square_note 0, 3, 1, 1903
	square_note 0, 3, 1, 1632
	square_note 0, 3, 1, 1643
	square_note 0, 3, 1, 1762
	square_note 0, 3, 1, 1904
	square_note 0, 3, 1, 1891
	square_note 0, 3, 1, 1898
	square_note 0, 3, 1, 1599
	square_note 0, 3, 1, 1686
	square_note 0, 3, 1, 1663
	square_note 0, 3, 1, 1657
	square_note 0, 3, 1, 1890
	square_note 0, 3, 1, 1899
	square_note 0, 3, 1, 1632
	square_note 0, 3, 1, 1913
	square_note 0, 3, 1, 1906
	square_note 0, 3, 1, 1627
	square_note 0, 3, 1, 1554
	square_note 0, 3, 1, 1989
	square_note 0, 3, 1, 1907
	square_note 0, 3, 1, 1677
	square_note 0, 3, 1, 1611
	square_note 0, 3, 1, 1642
	square_note 0, 3, 1, 1953
	square_note 0, 3, 1, 1910
	square_note 0, 3, 1, 1757
	square_note 0, 3, 1, 1918
	square_note 0, 3, 1, 1957
	square_note 0, 3, 1, 1915
	square_note 0, 3, 1, 1452
	square_note 0, 3, 1, 1780
	square_note 0, 3, 1, 1906
	square_note 0, 3, 1, 1616
	square_note 0, 3, 1, 1677
	square_note 0, 3, 1, 1622
	square_note 0, 3, 1, 1645
	square_note 0, 3, 1, 1567
	square_note 0, 3, 1, 1775
	square_note 0, 3, 1, 1668
	square_note 0, 3, 1, 1795
	square_note 0, 3, 1, 1948
	square_note 0, 3, 1, 1808
	square_note 0, 3, 1, 1938
	square_note 0, 3, 1, 1925
	square_note 0, 3, 1, 1919
	square_note 0, 3, 1, 1950
	square_note 0, 3, 1, 1929
	square_note 0, 3, 1, 1920
	square_note 0, 0, 1, 1841
	square_note 0, 0, 1, 1817
	square_note 0, 0, 1, 1945
	square_note 0, 0, 1, 1926
	square_note 0, 0, 1, 1915
	square_note 0, 0, 1, 1942
	square_note 1, 0, 1, 1924
	square_note 0, 0, 1, 1250
	square_note 0, 0, 1, 1988
	square_note 0, 0, 1, 1709
	sound_ret

Cry_Blastoise_Siren_Ch8:
	noise_note 0, 0, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 2, 9, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 3, 9, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 7, 9, 8, 75
	noise_note 0, 11, 8, 75
	noise_note 19, 9, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 2, 7, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 4, 5, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 11, 0, 8, 75
	sound_ret
