; Generated by Siren 2.0.0
; Source: celebi.wav
; Effect: Auto · based on Precise
; Volume: 100%
; Fade In: No
; Fade Out: No
; Channels: 1, 2, 3, 4
; Pitch Level: 0
; Resonance Level: -19
; Weight Level: -19
; Intonation Level: 16
; Texture Level: 23
; Breathiness Level: -42
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Celebi:
	channel_count 4
	channel 5, Cry_Celebi_Ch5
	channel 6, Cry_Celebi_Ch6
	channel 7, Cry_Celebi_Ch7
	channel 8, Cry_Celebi_Ch8

Cry_Celebi_Ch5:
	duty_cycle 2
	square_note 0, 12, 8, 1870
	square_note 1, 12, 8, 1972
	duty_cycle 1
	square_note 0, 12, 8, 1559
	square_note 0, 12, 8, 1600
	duty_cycle 2
	square_note 0, 12, 8, 1595
	square_note 0, 12, 8, 1611
	duty_cycle 3
	square_note 0, 12, 8, 1545
	duty_cycle 1
	square_note 1, 12, 8, 1576
	duty_cycle 2
	square_note 0, 12, 8, 1826
	square_note 0, 12, 8, 1807
	square_note 0, 12, 8, 1827
	duty_cycle 1
	square_note 0, 12, 8, 1905
	duty_cycle 3
	square_note 1, 12, 8, 1905
	duty_cycle 2
	square_note 0, 12, 8, 1807
	square_note 0, 12, 8, 1798
	duty_cycle 1
	square_note 1, 12, 8, 1899
	duty_cycle 0
	square_note 1, 12, 8, 1747
	duty_cycle 1
	square_note 2, 12, 8, 1890
	square_note 2, 12, 8, 1879
	duty_cycle 0
	square_note 1, 12, 8, 1702
	duty_cycle 2
	square_note 0, 12, 8, 1960
	duty_cycle 1
	square_note 0, 12, 8, 1872
	duty_cycle 0
	square_note 0, 12, 8, 1693
	duty_cycle 1
	square_note 0, 12, 8, 1695
	square_note 1, 10, 8, 1863
	duty_cycle 0
	square_note 0, 10, 8, 1680
	duty_cycle 1
	square_note 0, 12, 8, 1680
	square_note 1, 8, 8, 1861
	duty_cycle 3
	square_note 0, 8, 8, 1858
	duty_cycle 1
	square_note 1, 3, 8, 1858
	duty_cycle 2
	square_note 0, 1, 8, 1956
	duty_cycle 0
	square_note 0, 1, 8, 1680
	duty_cycle 3
	square_note 0, 1, 8, 1680
	duty_cycle 1
	square_note 2, 1, 8, 1861
	sound_ret

Cry_Celebi_Ch6:
	square_note 4, 0, 8, 0
	duty_cycle 3
	square_note 0, 8, 8, 1976
	duty_cycle 0
	square_note 0, 8, 8, 1976
	duty_cycle 1
	square_note 0, 7, 8, 1976
	duty_cycle 3
	square_note 1, 8, 8, 1976
	duty_cycle 2
	square_note 0, 7, 8, 1975
	square_note 0, 11, 8, 1975
	square_note 0, 0, 8, 0
	duty_cycle 3
	square_note 0, 11, 8, 1809
	duty_cycle 1
	square_note 0, 9, 8, 1815
	duty_cycle 2
	square_note 0, 8, 8, 1827
	duty_cycle 3
	square_note 0, 11, 8, 1902
	duty_cycle 1
	square_note 0, 12, 8, 1900
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 8, 8, 1972
	square_note 0, 8, 8, 1763
	square_note 0, 6, 8, 1763
	square_note 0, 9, 8, 1748
	square_note 5, 0, 8, 0
	square_note 0, 9, 8, 1735
	square_note 0, 9, 8, 1722
	square_note 1, 5, 8, 1722
	square_note 0, 7, 8, 1722
	square_note 0, 7, 8, 1715
	square_note 2, 5, 8, 1715
	square_note 8, 0, 8, 0
	sound_ret

Cry_Celebi_Ch7:
	square_note 0, 1, 3, 1994
	square_note 1, 1, 1, 2011
	square_note 0, 1, 7, 1767
	square_note 0, 1, 5, 1451
	square_note 0, 1, 2, 2011
	square_note 0, 1, 4, 1925
	square_note 0, 1, 0, 2011
	square_note 0, 1, 9, 1877
	square_note 0, 1, 0, 1955
	square_note 0, 1, 7, 1838
	square_note 0, 1, 1, 1941
	square_note 0, 1, 5, 1883
	square_note 0, 1, 4, 1883
	square_note 0, 1, 9, 1847
	square_note 0, 1, 2, 1976
	square_note 0, 1, 0, 1879
	square_note 0, 1, 8, 1367
	square_note 1, 1, 5, 1824
	square_note 0, 1, 0, 1908
	square_note 0, 1, 6, 1767
	square_note 0, 1, 4, 1367
	square_note 0, 1, 3, 1874
	square_note 1, 1, 2, 1884
	square_note 0, 1, 4, 1871
	square_note 0, 1, 7, 1419
	square_note 0, 1, 1, 1928
	square_note 0, 1, 8, 1772
	square_note 0, 1, 3, 1892
	square_note 0, 1, 3, 1852
	square_note 0, 1, 1, 1955
	square_note 0, 1, 1, 1991
	square_note 0, 1, 3, 1852
	square_note 0, 1, 1, 1852
	square_note 1, 1, 1, 1952
	square_note 0, 1, 6, 1838
	square_note 0, 1, 3, 1838
	square_note 0, 1, 1, 1847
	square_note 0, 3, 2, 1635
	square_note 1, 3, 2, 1957
	square_note 1, 3, 1, 1880
	square_note 0, 3, 0, 1987
	square_note 0, 3, 1, 2001
	square_note 0, 3, 3, 1957
	sound_ret

Cry_Celebi_Ch8:
	noise_note 37, 15, 8, 100
	noise_note 2, 14, 8, 100
	noise_note 0, 7, 8, 100
	noise_note 0, 4, 8, 100
	noise_note 0, 0, 8, 0
	noise_note 2, 4, 8, 100
	noise_note 1, 0, 8, 0
	sound_ret
