; Generated by Siren
; Source: scizor.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Scizor_Siren:
	channel_count 3
	channel 5, Cry_Scizor_Siren_Ch5
	channel 6, Cry_Scizor_Siren_Ch6
	channel 8, Cry_Scizor_Siren_Ch8

Cry_Scizor_Siren_Ch5:
	duty_cycle 2
	square_note 0, 10, 8, 1809
	duty_cycle 1
	square_note 0, 13, 8, 1483
	duty_cycle 0
	square_note 0, 13, 8, 1040
	duty_cycle 2
	square_note 0, 13, 8, 1795
	duty_cycle 1
	square_note 0, 13, 8, 1577
	duty_cycle 0
	square_note 0, 13, 8, 956
	square_note 0, 13, 8, 1393
	duty_cycle 2
	square_note 0, 13, 8, 1790
	square_note 0, 13, 8, 1268
	duty_cycle 3
	square_note 0, 13, 8, 1782
	duty_cycle 0
	square_note 0, 13, 8, 1218
	duty_cycle 2
	square_note 0, 13, 8, 1790
	square_note 0, 13, 8, 1379
	square_note 0, 13, 8, 1393
	duty_cycle 1
	square_note 0, 13, 8, 1617
	duty_cycle 2
	square_note 0, 13, 8, 1826
	square_note 0, 13, 8, 1343
	square_note 0, 13, 8, 1818
	duty_cycle 3
	square_note 0, 13, 8, 1386
	duty_cycle 2
	square_note 0, 13, 8, 1823
	duty_cycle 0
	square_note 0, 13, 8, 1112
	duty_cycle 2
	square_note 0, 13, 8, 1511
	duty_cycle 3
	square_note 0, 13, 8, 1818
	duty_cycle 2
	square_note 0, 13, 8, 1937
	duty_cycle 0
	square_note 0, 13, 8, 1707
	square_note 0, 13, 8, 1934
	duty_cycle 1
	square_note 0, 13, 8, 1934
	duty_cycle 3
	square_note 0, 13, 8, 1937
	duty_cycle 2
	square_note 0, 13, 8, 1935
	duty_cycle 0
	square_note 0, 13, 8, 1628
	square_note 0, 13, 8, 1831
	duty_cycle 2
	square_note 0, 13, 8, 1883
	square_note 0, 13, 8, 1877
	duty_cycle 1
	square_note 0, 13, 8, 1891
	square_note 0, 13, 8, 1696
	duty_cycle 2
	square_note 0, 13, 8, 1887
	square_note 0, 13, 8, 1229
	duty_cycle 0
	square_note 0, 13, 8, 1320
	duty_cycle 2
	square_note 0, 13, 8, 1249
	square_note 0, 13, 8, 1844
	duty_cycle 0
	square_note 0, 13, 8, 1112
	duty_cycle 2
	square_note 0, 13, 8, 1511
	square_note 0, 13, 8, 1834
	square_note 0, 13, 8, 1843
	square_note 0, 13, 8, 1197
	square_note 0, 12, 8, 1835
	square_note 0, 13, 8, 1832
	square_note 0, 13, 8, 1843
	square_note 0, 10, 8, 1239
	duty_cycle 1
	square_note 0, 11, 8, 1186
	duty_cycle 2
	square_note 0, 10, 8, 1822
	square_note 0, 11, 8, 1826
	duty_cycle 0
	square_note 0, 12, 8, 1835
	duty_cycle 2
	square_note 0, 10, 8, 1835
	square_note 0, 10, 8, 1820
	square_note 0, 10, 8, 1835
	square_note 0, 9, 8, 1818
	square_note 0, 7, 8, 1802
	square_note 0, 7, 8, 1816
	square_note 0, 5, 8, 1838
	square_note 0, 5, 8, 1801
	square_note 0, 3, 8, 1805
	square_note 0, 3, 8, 1795
	square_note 0, 2, 8, 1792
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Scizor_Siren_Ch6:
	duty_cycle 2
	square_note 0, 6, 8, 1625
	square_note 0, 6, 8, 1646
	square_note 0, 7, 8, 1593
	square_note 0, 0, 8, 0
	square_note 0, 5, 8, 1746
	duty_cycle 0
	square_note 0, 7, 8, 1782
	square_note 0, 9, 8, 1788
	square_note 0, 5, 8, 1831
	square_note 0, 5, 8, 1796
	square_note 0, 7, 8, 1824
	duty_cycle 3
	square_note 0, 6, 8, 1817
	duty_cycle 0
	square_note 0, 6, 8, 1832
	duty_cycle 2
	square_note 0, 5, 8, 1821
	square_note 0, 8, 8, 1833
	square_note 0, 6, 8, 1842
	square_note 0, 5, 8, 1736
	square_note 0, 7, 8, 1761
	square_note 0, 7, 8, 1682
	square_note 0, 5, 8, 1692
	duty_cycle 0
	square_note 0, 5, 8, 1692
	duty_cycle 3
	square_note 0, 6, 8, 1818
	square_note 0, 8, 8, 1816
	duty_cycle 0
	square_note 0, 6, 8, 1925
	duty_cycle 3
	square_note 0, 7, 8, 1920
	duty_cycle 0
	square_note 0, 6, 8, 1935
	duty_cycle 2
	square_note 0, 9, 8, 1879
	duty_cycle 0
	square_note 0, 7, 8, 1887
	duty_cycle 2
	square_note 0, 7, 8, 1890
	square_note 0, 8, 8, 1887
	square_note 0, 8, 8, 1891
	square_note 0, 8, 8, 1865
	square_note 0, 5, 8, 1835
	duty_cycle 0
	square_note 0, 8, 8, 1892
	duty_cycle 1
	square_note 0, 7, 8, 1849
	duty_cycle 3
	square_note 0, 9, 8, 1843
	duty_cycle 2
	square_note 0, 5, 8, 1820
	square_note 0, 6, 8, 1887
	duty_cycle 0
	square_note 0, 7, 8, 1845
	duty_cycle 3
	square_note 0, 8, 8, 1849
	duty_cycle 2
	square_note 0, 5, 8, 1745
	square_note 0, 6, 8, 1818
	square_note 0, 8, 8, 1824
	square_note 0, 0, 8, 0
	square_note 0, 6, 8, 1795
	square_note 0, 6, 8, 1815
	square_note 0, 0, 8, 0
	duty_cycle 0
	square_note 0, 5, 8, 1753
	square_note 0, 5, 8, 1817
	duty_cycle 2
	square_note 0, 5, 8, 1819
	duty_cycle 0
	square_note 0, 6, 8, 1839
	square_note 0, 6, 8, 1942
	square_note 0, 5, 8, 1943
	duty_cycle 3
	square_note 0, 5, 8, 1946
	duty_cycle 2
	square_note 0, 5, 8, 1945
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	duty_cycle 0
	square_note 0, 4, 8, 1844
	square_note 0, 3, 8, 1844
	square_note 0, 0, 8, 0
	square_note 0, 3, 8, 1835
	square_note 0, 2, 8, 1835
	duty_cycle 2
	square_note 0, 2, 8, 1942
	square_note 0, 1, 8, 1837
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Scizor_Siren_Ch8:
	noise_note 0, 7, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	sound_ret
