; Generated by Siren
; Source: suicune.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Suicune_Siren:
	channel_count 3
	channel 5, Cry_Suicune_Siren_Ch5
	channel 6, Cry_Suicune_Siren_Ch6
	channel 8, Cry_Suicune_Siren_Ch8

Cry_Suicune_Siren_Ch5:
	duty_cycle 2
	square_note 0, 3, 8, 1837
	square_note 0, 13, 8, 1839
	square_note 0, 13, 8, 1807
	square_note 0, 13, 8, 1834
	duty_cycle 1
	square_note 0, 13, 8, 1835
	duty_cycle 0
	square_note 0, 13, 8, 1312
	duty_cycle 2
	square_note 0, 13, 8, 1836
	square_note 0, 13, 8, 1834
	square_note 0, 13, 8, 1852
	duty_cycle 1
	square_note 0, 13, 8, 1662
	duty_cycle 2
	square_note 0, 13, 8, 1820
	duty_cycle 3
	square_note 0, 13, 8, 1614
	duty_cycle 1
	square_note 0, 13, 8, 1843
	square_note 0, 13, 8, 1633
	duty_cycle 3
	square_note 0, 13, 8, 1812
	duty_cycle 2
	square_note 0, 13, 8, 1816
	square_note 0, 13, 8, 1814
	square_note 0, 13, 8, 1830
	square_note 0, 13, 8, 1790
	square_note 0, 13, 8, 1617
	square_note 0, 13, 8, 1804
	square_note 0, 13, 8, 1815
	square_note 0, 13, 8, 1891
	square_note 0, 13, 8, 1889
	square_note 0, 13, 8, 1926
	square_note 0, 13, 8, 1891
	square_note 0, 13, 8, 1890
	square_note 0, 13, 8, 1888
	duty_cycle 1
	square_note 0, 13, 8, 1890
	duty_cycle 2
	square_note 0, 13, 8, 1927
	square_note 0, 13, 8, 1929
	square_note 0, 13, 8, 1892
	duty_cycle 1
	square_note 0, 13, 8, 1892
	duty_cycle 2
	square_note 0, 13, 8, 1930
	square_note 0, 13, 8, 1886
	square_note 0, 13, 8, 1885
	duty_cycle 1
	square_note 0, 13, 8, 1887
	duty_cycle 2
	square_note 0, 13, 8, 1899
	square_note 0, 13, 8, 1931
	duty_cycle 1
	square_note 0, 13, 8, 1890
	duty_cycle 2
	square_note 0, 13, 8, 1896
	square_note 0, 13, 8, 1885
	square_note 0, 13, 8, 1887
	square_note 0, 13, 8, 1882
	square_note 0, 13, 8, 1878
	duty_cycle 1
	square_note 0, 13, 8, 1872
	duty_cycle 2
	square_note 0, 13, 8, 1882
	square_note 0, 13, 8, 1881
	square_note 0, 13, 8, 1870
	square_note 0, 13, 8, 1869
	square_note 0, 13, 8, 1874
	square_note 0, 13, 8, 1872
	square_note 0, 5, 8, 1884
	square_note 0, 3, 8, 1874
	square_note 0, 0, 8, 0
	square_note 0, 1, 8, 1886
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 1, 8, 1870
	square_note 0, 1, 8, 1869
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Suicune_Siren_Ch6:
	duty_cycle 3
	square_note 0, 1, 8, 1938
	square_note 0, 6, 8, 1937
	square_note 0, 7, 8, 1938
	duty_cycle 2
	square_note 0, 5, 8, 1876
	square_note 0, 6, 8, 1896
	square_note 0, 7, 8, 1885
	square_note 0, 5, 8, 1874
	square_note 0, 5, 8, 1863
	square_note 0, 6, 8, 1876
	duty_cycle 1
	square_note 0, 9, 8, 1881
	duty_cycle 2
	square_note 0, 5, 8, 1861
	duty_cycle 1
	square_note 0, 6, 8, 1820
	duty_cycle 3
	square_note 0, 9, 8, 1813
	duty_cycle 0
	square_note 0, 6, 8, 1812
	duty_cycle 3
	square_note 0, 8, 8, 1638
	duty_cycle 2
	square_note 0, 7, 8, 1636
	square_note 0, 0, 8, 0
	duty_cycle 0
	square_note 0, 5, 8, 1722
	duty_cycle 3
	square_note 0, 7, 8, 1611
	square_note 0, 6, 8, 1804
	duty_cycle 2
	square_note 0, 8, 8, 1890
	square_note 0, 8, 8, 1890
	square_note 0, 6, 8, 1810
	duty_cycle 3
	square_note 0, 5, 8, 1793
	duty_cycle 2
	square_note 0, 8, 8, 1895
	square_note 0, 7, 8, 1927
	square_note 0, 5, 8, 1930
	square_note 0, 0, 8, 0
	square_note 0, 8, 8, 1927
	square_note 0, 8, 8, 1891
	square_note 0, 8, 8, 1887
	square_note 0, 5, 8, 1931
	square_note 0, 5, 8, 1932
	duty_cycle 3
	square_note 0, 6, 8, 1888
	duty_cycle 2
	square_note 0, 7, 8, 1929
	square_note 0, 5, 8, 1936
	square_note 0, 7, 8, 1933
	square_note 0, 6, 8, 1929
	square_note 0, 9, 8, 1890
	square_note 0, 5, 8, 1926
	square_note 0, 7, 8, 1925
	square_note 0, 6, 8, 1927
	square_note 0, 8, 8, 1930
	square_note 0, 6, 8, 1932
	square_note 0, 8, 8, 1928
	square_note 0, 7, 8, 1925
	square_note 0, 6, 8, 1926
	square_note 0, 8, 8, 1928
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 3, 8, 1867
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 1, 8, 1928
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Suicune_Siren_Ch8:
	noise_note 0, 2, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 6, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 6, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 6, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 6, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 0, 6, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	sound_ret
