; Generated by Siren
; Source: typhlosion.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Typhlosion_Siren:
	channel_count 4
	channel 5, Cry_Typhlosion_Siren_Ch5
	channel 6, Cry_Typhlosion_Siren_Ch6
	channel 7, Cry_Typhlosion_Siren_Ch7
	channel 8, Cry_Typhlosion_Siren_Ch8

Cry_Typhlosion_Siren_Ch5:
	square_note 0, 0, 8, 0
	duty_cycle 0
	square_note 0, 13, 8, 1832
	duty_cycle 1
	square_note 0, 13, 8, 1577
	square_note 0, 13, 8, 1249
	square_note 0, 13, 8, 1577
	duty_cycle 2
	square_note 0, 13, 8, 1684
	square_note 0, 13, 8, 1577
	square_note 0, 13, 8, 1573
	square_note 0, 13, 8, 1040
	square_note 0, 13, 8, 1365
	duty_cycle 0
	square_note 0, 13, 8, 1320
	duty_cycle 2
	square_note 0, 13, 8, 1511
	duty_cycle 0
	square_note 0, 13, 8, 1150
	duty_cycle 2
	square_note 0, 13, 8, 1646
	duty_cycle 1
	square_note 0, 13, 8, 1218
	square_note 0, 13, 8, 1150
	duty_cycle 2
	square_note 0, 13, 8, 1418
	duty_cycle 1
	square_note 0, 13, 8, 956
	duty_cycle 2
	square_note 0, 13, 8, 956
	square_note 0, 13, 8, 1866
	square_note 0, 13, 8, 1502
	square_note 0, 13, 8, 1866
	duty_cycle 0
	square_note 0, 13, 8, 1684
	duty_cycle 3
	square_note 0, 13, 8, 1684
	duty_cycle 1
	square_note 0, 13, 8, 1680
	square_note 0, 13, 8, 1690
	duty_cycle 3
	square_note 0, 13, 8, 956
	duty_cycle 2
	square_note 0, 13, 8, 1070
	square_note 0, 13, 8, 1866
	square_note 0, 13, 8, 1865
	duty_cycle 1
	square_note 0, 13, 8, 956
	duty_cycle 0
	square_note 0, 13, 8, 956
	duty_cycle 3
	square_note 0, 13, 8, 1678
	duty_cycle 2
	square_note 1, 13, 8, 1861
	square_note 0, 13, 8, 1860
	square_note 0, 13, 8, 1859
	square_note 0, 13, 8, 1857
	square_note 0, 13, 8, 1858
	duty_cycle 3
	square_note 0, 13, 8, 1667
	duty_cycle 2
	square_note 0, 13, 8, 1859
	square_note 1, 13, 8, 1856
	square_note 0, 13, 8, 1858
	square_note 0, 13, 8, 1856
	duty_cycle 1
	square_note 0, 13, 8, 1646
	duty_cycle 3
	square_note 0, 13, 8, 1648
	duty_cycle 1
	square_note 0, 13, 8, 1249
	duty_cycle 3
	square_note 0, 13, 8, 1667
	duty_cycle 2
	square_note 0, 13, 8, 1855
	duty_cycle 1
	square_note 0, 13, 8, 1862
	square_note 0, 13, 8, 1671
	duty_cycle 3
	square_note 0, 13, 8, 1667
	duty_cycle 2
	square_note 0, 13, 8, 1856
	duty_cycle 1
	square_note 0, 13, 8, 1662
	square_note 0, 13, 8, 1669
	duty_cycle 0
	square_note 0, 13, 8, 1497
	duty_cycle 2
	square_note 0, 13, 8, 1848
	duty_cycle 1
	square_note 0, 13, 8, 1646
	square_note 0, 13, 8, 1320
	duty_cycle 2
	square_note 0, 13, 8, 956
	square_note 0, 13, 8, 1633
	square_note 0, 13, 8, 1656
	square_note 0, 13, 8, 1638
	square_note 0, 13, 8, 1669
	square_note 0, 13, 8, 1412
	duty_cycle 1
	square_note 0, 13, 8, 1641
	square_note 0, 13, 8, 1328
	square_note 0, 13, 8, 956
	duty_cycle 2
	square_note 0, 13, 8, 1532
	duty_cycle 3
	square_note 0, 13, 8, 1430
	square_note 0, 13, 8, 1773
	duty_cycle 0
	square_note 0, 12, 8, 1174
	duty_cycle 2
	square_note 0, 13, 8, 1493
	duty_cycle 1
	square_note 0, 13, 8, 1320
	duty_cycle 0
	square_note 0, 13, 8, 956
	duty_cycle 2
	square_note 0, 12, 8, 1277
	square_note 0, 13, 8, 1436
	duty_cycle 0
	square_note 0, 13, 8, 1024
	duty_cycle 1
	square_note 0, 13, 8, 1258
	duty_cycle 2
	square_note 0, 13, 8, 1751
	duty_cycle 1
	square_note 0, 13, 8, 1162
	duty_cycle 2
	square_note 0, 11, 8, 1112
	duty_cycle 1
	square_note 0, 13, 8, 1358
	square_note 0, 13, 8, 1473
	duty_cycle 2
	square_note 0, 13, 8, 1098
	square_note 0, 13, 8, 1590
	square_note 0, 13, 8, 1328
	duty_cycle 0
	square_note 0, 13, 8, 974
	duty_cycle 2
	square_note 0, 10, 8, 1277
	square_note 0, 12, 8, 1463
	duty_cycle 0
	square_note 0, 10, 8, 1008
	duty_cycle 1
	square_note 0, 11, 8, 1351
	duty_cycle 2
	square_note 0, 11, 8, 1751
	duty_cycle 0
	square_note 0, 11, 8, 1218
	square_note 0, 6, 8, 974
	duty_cycle 2
	square_note 0, 8, 8, 1372
	square_note 0, 10, 8, 1497
	square_note 0, 7, 8, 1070
	square_note 0, 6, 8, 1757
	square_note 0, 4, 8, 1577
	square_note 0, 3, 8, 1638
	square_note 0, 1, 8, 1473
	duty_cycle 1
	square_note 0, 2, 8, 1577
	duty_cycle 0
	square_note 0, 1, 8, 1024
	duty_cycle 3
	square_note 0, 1, 8, 1070
	duty_cycle 2
	square_note 0, 1, 8, 1208
	square_note 0, 0, 8, 0
	square_note 0, 1, 8, 1277
	square_note 5, 0, 8, 0
	sound_ret

Cry_Typhlosion_Siren_Ch6:
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 0, 8, 8, 1519
	square_note 0, 9, 8, 1511
	square_note 0, 9, 8, 1519
	duty_cycle 1
	square_note 0, 8, 8, 1559
	square_note 2, 0, 8, 0
	duty_cycle 0
	square_note 0, 8, 8, 1865
	square_note 0, 9, 8, 1865
	square_note 0, 8, 8, 1865
	duty_cycle 2
	square_note 0, 7, 8, 1864
	duty_cycle 0
	square_note 0, 7, 8, 1864
	duty_cycle 2
	square_note 0, 8, 8, 1866
	square_note 0, 7, 8, 1864
	duty_cycle 0
	square_note 0, 7, 8, 1866
	duty_cycle 2
	square_note 0, 7, 8, 1867
	duty_cycle 1
	square_note 0, 8, 8, 1864
	square_note 2, 0, 8, 0
	duty_cycle 2
	square_note 0, 8, 8, 1858
	duty_cycle 0
	square_note 0, 6, 8, 1854
	square_note 0, 0, 8, 0
	duty_cycle 1
	square_note 0, 9, 8, 1861
	duty_cycle 3
	square_note 0, 7, 8, 1867
	square_note 2, 0, 8, 0
	duty_cycle 2
	square_note 0, 6, 8, 1867
	square_note 0, 9, 8, 1864
	square_note 0, 6, 8, 1930
	square_note 0, 6, 8, 1929
	square_note 0, 6, 8, 1928
	duty_cycle 3
	square_note 0, 6, 8, 1929
	square_note 0, 7, 8, 1921
	square_note 0, 6, 8, 1921
	square_note 6, 0, 8, 0
	duty_cycle 2
	square_note 0, 8, 8, 1855
	square_note 0, 5, 8, 1857
	duty_cycle 3
	square_note 0, 8, 8, 1860
	duty_cycle 2
	square_note 0, 6, 8, 1849
	square_note 1, 0, 8, 0
	square_note 0, 6, 8, 1852
	duty_cycle 1
	square_note 0, 5, 8, 1865
	square_note 2, 0, 8, 0
	duty_cycle 3
	square_note 0, 9, 8, 1669
	duty_cycle 2
	square_note 0, 8, 8, 1699
	duty_cycle 1
	square_note 0, 10, 8, 1418
	duty_cycle 3
	square_note 0, 7, 8, 1418
	duty_cycle 2
	square_note 0, 8, 8, 1399
	square_note 0, 9, 8, 1424
	duty_cycle 3
	square_note 0, 8, 8, 1399
	duty_cycle 2
	square_note 0, 6, 8, 1418
	duty_cycle 3
	square_note 0, 7, 8, 1447
	duty_cycle 2
	square_note 0, 7, 8, 1488
	square_note 0, 8, 8, 1483
	square_note 0, 0, 8, 0
	square_note 0, 8, 8, 1559
	square_note 0, 6, 8, 1583
	square_note 1, 0, 8, 0
	square_note 0, 7, 8, 1648
	duty_cycle 0
	square_note 0, 8, 8, 1646
	square_note 0, 8, 8, 1544
	duty_cycle 2
	square_note 0, 6, 8, 1559
	square_note 0, 0, 8, 0
	duty_cycle 3
	square_note 0, 8, 8, 1506
	duty_cycle 2
	square_note 0, 9, 8, 1473
	square_note 1, 0, 8, 0
	square_note 0, 9, 8, 1303
	duty_cycle 0
	square_note 0, 5, 8, 1268
	duty_cycle 2
	square_note 0, 9, 8, 1239
	square_note 1, 0, 8, 0
	square_note 0, 9, 8, 1540
	square_note 0, 9, 8, 1573
	square_note 0, 0, 8, 0
	duty_cycle 3
	square_note 0, 7, 8, 1386
	duty_cycle 2
	square_note 0, 7, 8, 1372
	square_note 5, 0, 8, 0
	square_note 0, 6, 8, 1424
	duty_cycle 1
	square_note 0, 4, 8, 1430
	square_note 15, 0, 8, 0
	sound_ret

Cry_Typhlosion_Siren_Ch7:
	square_note 0, 0, 0, 0
	square_note 0, 1, 7, 1274
	square_note 0, 1, 9, 1867
	square_note 0, 1, 5, 1941
	square_note 0, 1, 7, 1167
	square_note 0, 1, 6, 1537
	square_note 0, 1, 7, 1136
	square_note 0, 1, 8, 1875
	square_note 0, 1, 1, 2016
	square_note 0, 1, 6, 1393
	square_note 0, 1, 4, 1795
	square_note 0, 1, 6, 1863
	square_note 0, 1, 5, 1754
	square_note 0, 1, 7, 1297
	square_note 0, 1, 7, 1318
	square_note 0, 1, 7, 1136
	square_note 0, 1, 6, 1871
	square_note 0, 1, 7, 1297
	square_note 0, 1, 6, 1721
	square_note 0, 1, 5, 1197
	square_note 0, 1, 7, 1297
	square_note 0, 1, 7, 1688
	square_note 0, 1, 8, 1751
	square_note 0, 0, 0, 0
	square_note 0, 1, 6, 1698
	square_note 0, 1, 8, 1740
	square_note 0, 1, 1, 2024
	square_note 0, 1, 1, 2016
	square_note 0, 1, 4, 1440
	square_note 0, 1, 7, 1136
	square_note 0, 1, 8, 1847
	square_note 0, 1, 7, 1297
	square_note 0, 1, 7, 1339
	square_note 0, 1, 6, 1481
	square_note 0, 1, 4, 1136
	square_note 1, 1, 5, 1136
	square_note 0, 1, 8, 1537
	square_note 0, 1, 4, 1468
	square_note 0, 1, 4, 1725
	square_note 0, 1, 6, 1859
	square_note 0, 1, 7, 1376
	square_note 0, 1, 5, 1758
	square_note 0, 1, 7, 1136
	square_note 0, 1, 8, 1393
	square_note 0, 1, 7, 1376
	square_note 0, 1, 4, 1733
	square_note 0, 1, 6, 1136
	square_note 0, 1, 4, 1608
	square_note 0, 1, 6, 1703
	square_note 0, 1, 9, 1737
	square_note 1, 1, 7, 1136
	square_note 0, 1, 7, 1826
	square_note 0, 1, 1, 2001
	square_note 0, 1, 7, 1339
	square_note 0, 1, 7, 1136
	square_note 0, 1, 7, 1250
	square_note 0, 1, 7, 1516
	square_note 0, 1, 7, 1816
	square_note 0, 1, 7, 1297
	square_note 0, 1, 1, 1950
	square_note 0, 1, 7, 1224
	square_note 0, 1, 4, 1493
	square_note 0, 1, 6, 1425
	square_note 0, 1, 4, 1871
	square_note 0, 1, 7, 1274
	square_note 0, 1, 5, 1136
	square_note 0, 1, 5, 1297
	square_note 0, 1, 7, 1136
	square_note 0, 1, 7, 1274
	square_note 0, 1, 7, 1136
	square_note 0, 1, 6, 1136
	square_note 0, 1, 4, 1136
	square_note 0, 1, 7, 1410
	square_note 0, 1, 7, 1847
	square_note 0, 1, 6, 1339
	square_note 0, 1, 9, 1864
	square_note 0, 1, 7, 1274
	square_note 0, 1, 7, 1136
	square_note 0, 1, 7, 1297
	square_note 0, 1, 3, 1798
	square_note 0, 1, 1, 1941
	square_note 0, 1, 7, 1136
	square_note 0, 1, 7, 1167
	square_note 0, 1, 4, 1921
	square_note 0, 1, 0, 1900
	square_note 0, 1, 7, 1136
	square_note 1, 1, 6, 1318
	square_note 0, 1, 6, 1575
	square_note 0, 1, 7, 1339
	square_note 0, 1, 7, 1136
	square_note 0, 1, 5, 1358
	square_note 0, 1, 1, 1816
	square_note 0, 2, 9, 1850
	square_note 0, 2, 7, 1136
	square_note 0, 1, 7, 1167
	square_note 0, 2, 3, 1918
	square_note 0, 2, 7, 1339
	square_note 0, 3, 5, 1629
	square_note 0, 3, 4, 1930
	square_note 0, 3, 6, 1274
	square_note 0, 3, 7, 1136
	square_note 0, 3, 4, 1911
	square_note 0, 3, 4, 1393
	square_note 0, 3, 1, 1887
	square_note 0, 0, 0, 0
	square_note 0, 3, 1, 1566
	square_note 5, 0, 0, 0
	sound_ret

Cry_Typhlosion_Siren_Ch8:
	noise_note 0, 0, 8, 0
	noise_note 0, 13, 8, 100
	noise_note 51, 15, 8, 100
	noise_note 0, 13, 8, 100
	noise_note 1, 15, 8, 100
	noise_note 0, 14, 8, 100
	noise_note 0, 15, 8, 100
	noise_note 0, 14, 8, 100
	noise_note 1, 15, 8, 100
	noise_note 0, 14, 8, 100
	noise_note 0, 12, 8, 100
	noise_note 4, 15, 8, 100
	noise_note 0, 13, 8, 100
	noise_note 0, 12, 8, 100
	noise_note 0, 13, 8, 100
	noise_note 0, 10, 8, 100
	noise_note 0, 14, 8, 100
	noise_note 1, 13, 8, 100
	noise_note 0, 10, 8, 100
	noise_note 1, 15, 8, 100
	noise_note 0, 12, 8, 100
	noise_note 1, 15, 8, 100
	noise_note 0, 9, 8, 100
	noise_note 1, 13, 8, 100
	noise_note 1, 12, 8, 100
	noise_note 1, 11, 8, 100
	noise_note 0, 9, 8, 100
	noise_note 0, 10, 8, 100
	noise_note 3, 9, 8, 100
	noise_note 0, 5, 8, 100
	noise_note 0, 6, 8, 100
	noise_note 0, 8, 8, 100
	noise_note 0, 6, 8, 100
	noise_note 0, 5, 8, 100
	noise_note 1, 3, 8, 100
	noise_note 3, 1, 8, 100
	noise_note 8, 0, 8, 0
	sound_ret
