; Generated by Siren
; Source: tyranitar.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Tyranitar_Siren:
	channel_count 3
	channel 5, Cry_Tyranitar_Siren_Ch5
	channel 6, Cry_Tyranitar_Siren_Ch6
	channel 8, Cry_Tyranitar_Siren_Ch8

Cry_Tyranitar_Siren_Ch5:
	square_note 0, 0, 8, 0
	duty_cycle 1
	square_note 0, 13, 8, 1503
	square_note 0, 13, 8, 1757
	duty_cycle 2
	square_note 0, 13, 8, 1535
	duty_cycle 1
	square_note 0, 13, 8, 934
	duty_cycle 2
	square_note 0, 13, 8, 1075
	duty_cycle 0
	square_note 0, 13, 8, 1263
	square_note 0, 13, 8, 1037
	duty_cycle 2
	square_note 0, 13, 8, 1330
	duty_cycle 1
	square_note 0, 13, 8, 828
	duty_cycle 0
	square_note 0, 13, 8, 1023
	square_note 0, 13, 8, 510
	duty_cycle 2
	square_note 0, 13, 8, 1559
	duty_cycle 1
	square_note 0, 13, 8, 901
	duty_cycle 2
	square_note 0, 13, 8, 745
	square_note 0, 13, 8, 570
	duty_cycle 1
	square_note 0, 13, 8, 1050
	square_note 0, 13, 8, 883
	square_note 0, 13, 8, 447
	square_note 0, 13, 8, 1532
	duty_cycle 0
	square_note 0, 13, 8, 1263
	duty_cycle 2
	square_note 0, 13, 8, 1423
	square_note 0, 13, 8, 767
	square_note 0, 13, 8, 1397
	square_note 0, 13, 8, 624
	square_note 0, 13, 8, 1302
	square_note 0, 13, 8, 1309
	duty_cycle 0
	square_note 0, 13, 8, 1379
	duty_cycle 2
	square_note 0, 13, 8, 1917
	duty_cycle 0
	square_note 0, 13, 8, 1287
	duty_cycle 2
	square_note 0, 13, 8, 1330
	square_note 0, 13, 8, 1379
	square_note 0, 13, 8, 1374
	duty_cycle 1
	square_note 0, 13, 8, 1402
	duty_cycle 2
	square_note 0, 13, 8, 1891
	square_note 0, 13, 8, 1356
	duty_cycle 0
	square_note 0, 13, 8, 1323
	duty_cycle 2
	square_note 0, 13, 8, 1423
	duty_cycle 1
	square_note 0, 13, 8, 1700
	duty_cycle 2
	square_note 1, 13, 8, 1362
	square_note 0, 13, 8, 1323
	duty_cycle 1
	square_note 0, 13, 8, 1294
	duty_cycle 2
	square_note 0, 13, 8, 1247
	square_note 0, 13, 8, 1349
	square_note 0, 13, 8, 1343
	square_note 0, 13, 8, 1294
	duty_cycle 0
	square_note 0, 13, 8, 1302
	duty_cycle 2
	square_note 0, 13, 8, 1888
	duty_cycle 1
	square_note 0, 13, 8, 1287
	square_note 0, 13, 8, 1323
	duty_cycle 2
	square_note 0, 13, 8, 1280
	duty_cycle 0
	square_note 0, 13, 8, 1294
	duty_cycle 2
	square_note 0, 13, 8, 1287
	duty_cycle 1
	square_note 0, 13, 8, 1309
	square_note 0, 13, 8, 1808
	duty_cycle 0
	square_note 0, 13, 8, 1316
	square_note 0, 13, 8, 1302
	duty_cycle 1
	square_note 0, 13, 8, 1287
	square_note 0, 13, 8, 1374
	duty_cycle 2
	square_note 0, 13, 8, 1239
	square_note 0, 12, 8, 1111
	square_note 0, 12, 8, 965
	duty_cycle 1
	square_note 0, 11, 8, 570
	duty_cycle 2
	square_note 0, 10, 8, 510
	square_note 0, 10, 8, 127
	square_note 0, 9, 8, 1272
	square_note 0, 7, 8, 1368
	square_note 0, 4, 8, 1280
	square_note 0, 4, 8, 1231
	duty_cycle 1
	square_note 0, 1, 8, 866
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Tyranitar_Siren_Ch6:
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 6, 8, 1443
	duty_cycle 1
	square_note 0, 7, 8, 1619
	duty_cycle 2
	square_note 0, 5, 8, 1483
	square_note 0, 6, 8, 1428
	square_note 0, 5, 8, 1221
	square_note 0, 5, 8, 1121
	square_note 0, 5, 8, 1194
	duty_cycle 0
	square_note 0, 7, 8, 1194
	duty_cycle 2
	square_note 0, 6, 8, 1050
	square_note 0, 6, 8, 788
	square_note 0, 5, 8, 847
	square_note 0, 7, 8, 1503
	square_note 0, 4, 8, 1528
	duty_cycle 0
	square_note 0, 5, 8, 1528
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 6, 8, 1499
	square_note 0, 4, 8, 1521
	square_note 0, 6, 8, 1349
	duty_cycle 1
	square_note 0, 5, 8, 1336
	duty_cycle 2
	square_note 0, 7, 8, 1448
	square_note 0, 6, 8, 1921
	square_note 0, 5, 8, 1914
	square_note 0, 4, 8, 1903
	square_note 0, 4, 8, 1914
	square_note 0, 0, 8, 0
	square_note 0, 7, 8, 1917
	square_note 0, 5, 8, 1915
	square_note 0, 5, 8, 1903
	square_note 0, 5, 8, 1900
	square_note 0, 5, 8, 1912
	square_note 0, 5, 8, 1871
	square_note 0, 4, 8, 1884
	square_note 0, 6, 8, 1896
	square_note 0, 5, 8, 1835
	square_note 0, 6, 8, 1894
	square_note 0, 5, 8, 1862
	square_note 0, 6, 8, 1796
	duty_cycle 0
	square_note 0, 5, 8, 1798
	duty_cycle 2
	square_note 1, 5, 8, 1438
	square_note 0, 3, 8, 1412
	square_note 0, 5, 8, 1385
	square_note 0, 5, 8, 1349
	square_note 0, 5, 8, 1433
	square_note 0, 4, 8, 1423
	square_note 0, 6, 8, 1804
	square_note 0, 4, 8, 1838
	duty_cycle 1
	square_note 0, 5, 8, 1798
	duty_cycle 2
	square_note 0, 4, 8, 1385
	square_note 0, 5, 8, 1213
	square_note 0, 5, 8, 1374
	square_note 0, 5, 8, 1174
	square_note 0, 5, 8, 1385
	square_note 0, 4, 8, 1397
	square_note 0, 5, 8, 1669
	square_note 0, 5, 8, 1402
	duty_cycle 0
	square_note 0, 5, 8, 1174
	square_note 0, 7, 8, 1385
	duty_cycle 2
	square_note 0, 6, 8, 1099
	square_note 0, 5, 8, 1099
	square_note 0, 0, 8, 0
	duty_cycle 0
	square_note 0, 4, 8, 1144
	duty_cycle 2
	square_note 0, 4, 8, 883
	square_note 0, 0, 8, 0
	square_note 0, 3, 8, 1231
	square_note 0, 3, 8, 1368
	square_note 0, 3, 8, 1272
	square_note 0, 2, 8, 1154
	square_note 0, 2, 8, 1336
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Tyranitar_Siren_Ch8:
	noise_note 0, 0, 8, 75
	noise_note 23, 8, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 2, 8, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 2, 7, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 8, 7, 8, 75
	noise_note 0, 6, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 3, 3, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 9, 0, 8, 75
	sound_ret
