; Generated by Siren 2.0.0
; Source: wartortle.wav
; Effect: Auto · based on Precise
; Volume: 100%
; Fade In: No
; Fade Out: No
; Channels: 1, 2, 3, 4
; Pitch Level: 0
; Resonance Level: -35
; Weight Level: -13
; Intonation Level: 0
; Texture Level: 60
; Breathiness Level: -70
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Wartortle_Siren:
	channel_count 4
	channel 5, Cry_Wartortle_Siren_Ch5
	channel 6, Cry_Wartortle_Siren_Ch6
	channel 7, Cry_Wartortle_Siren_Ch7
	channel 8, Cry_Wartortle_Siren_Ch8

Cry_Wartortle_Siren_Ch5:
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 2, 8, 1997
	square_note 0, 3, 8, 1224
	duty_cycle 3
	square_note 0, 3, 8, 1422
	duty_cycle 1
	square_note 0, 3, 8, 1468
	duty_cycle 2
	square_note 0, 3, 8, 1992
	duty_cycle 1
	square_note 0, 3, 8, 1508
	duty_cycle 2
	square_note 0, 3, 8, 1785
	square_note 0, 3, 8, 1775
	square_note 0, 3, 8, 1836
	square_note 0, 2, 8, 1776
	duty_cycle 0
	square_note 0, 3, 8, 1843
	duty_cycle 2
	square_note 0, 2, 8, 1775
	duty_cycle 1
	square_note 0, 2, 8, 1835
	square_note 0, 3, 8, 1824
	duty_cycle 0
	square_note 0, 2, 8, 1834
	duty_cycle 2
	square_note 0, 3, 8, 1759
	duty_cycle 0
	square_note 0, 2, 8, 1836
	duty_cycle 2
	square_note 0, 2, 8, 1778
	square_note 0, 3, 8, 1771
	duty_cycle 0
	square_note 0, 7, 8, 1822
	duty_cycle 2
	square_note 0, 2, 8, 1428
	square_note 0, 2, 8, 1786
	duty_cycle 0
	square_note 0, 6, 8, 1265
	duty_cycle 2
	square_note 0, 2, 8, 2002
	square_note 1, 2, 8, 1839
	square_note 0, 2, 8, 1782
	duty_cycle 0
	square_note 0, 2, 8, 1843
	duty_cycle 1
	square_note 0, 2, 8, 1446
	duty_cycle 2
	square_note 2, 2, 8, 1994
	duty_cycle 1
	square_note 0, 2, 8, 1551
	duty_cycle 2
	square_note 0, 2, 8, 1983
	duty_cycle 3
	square_note 0, 2, 8, 1636
	duty_cycle 2
	square_note 0, 2, 8, 1636
	square_note 0, 2, 8, 1538
	square_note 0, 2, 8, 1224
	duty_cycle 1
	square_note 0, 2, 8, 1639
	duty_cycle 0
	square_note 0, 1, 8, 715
	square_note 0, 1, 8, 1201
	duty_cycle 2
	square_note 0, 1, 8, 1733
	duty_cycle 1
	square_note 0, 1, 8, 1521
	square_note 0, 1, 8, 1433
	duty_cycle 3
	square_note 0, 1, 8, 1178
	duty_cycle 0
	square_note 0, 1, 8, 1311
	duty_cycle 1
	square_note 0, 1, 8, 1489
	square_note 0, 1, 8, 1367
	duty_cycle 2
	square_note 0, 1, 8, 1722
	square_note 0, 1, 8, 1498
	square_note 0, 1, 8, 1433
	square_note 6, 0, 8, 0
	sound_ret

Cry_Wartortle_Siren_Ch6:
	square_note 5, 0, 8, 0
	duty_cycle 2
	square_note 2, 6, 8, 1997
	square_note 2, 0, 8, 0
	square_note 1, 6, 8, 1995
	square_note 1, 0, 8, 0
	square_note 0, 7, 8, 1996
	square_note 11, 5, 8, 1996
	square_note 0, 7, 8, 1996
	square_note 0, 5, 8, 1996
	square_note 5, 0, 8, 0
	duty_cycle 3
	square_note 1, 5, 8, 1841
	square_note 3, 0, 8, 0
	square_note 1, 2, 8, 1581
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 2, 8, 1415
	square_note 0, 2, 8, 1402
	square_note 10, 0, 8, 0
	sound_ret

Cry_Wartortle_Siren_Ch7:
	square_note 0, 0, 0, 0
	square_note 0, 1, 1, 2023
	square_note 0, 1, 5, 1636
	square_note 0, 1, 6, 1735
	square_note 0, 1, 2, 1758
	square_note 0, 1, 1, 2020
	square_note 0, 1, 7, 1778
	square_note 0, 1, 7, 1917
	square_note 0, 1, 9, 1917
	square_note 0, 1, 4, 1942
	square_note 0, 1, 4, 1912
	square_note 0, 1, 7, 1946
	square_note 0, 1, 8, 1911
	square_note 0, 1, 7, 1942
	square_note 0, 1, 4, 1942
	square_note 0, 1, 7, 1942
	square_note 0, 1, 9, 1904
	square_note 0, 1, 7, 1942
	square_note 0, 1, 9, 1913
	square_note 0, 1, 4, 1913
	square_note 0, 0, 0, 0
	square_note 0, 1, 6, 1738
	square_note 0, 1, 9, 1917
	square_note 0, 0, 0, 0
	square_note 0, 1, 1, 2025
	square_note 0, 1, 7, 1944
	square_note 0, 1, 1, 1944
	square_note 0, 1, 8, 1915
	square_note 0, 1, 4, 1946
	square_note 0, 1, 5, 1747
	square_note 2, 1, 1, 2021
	square_note 0, 1, 7, 1799
	square_note 0, 1, 1, 2015
	square_note 0, 1, 7, 1842
	square_note 0, 1, 4, 1842
	square_note 0, 1, 8, 1794
	square_note 0, 1, 7, 1636
	square_note 0, 1, 7, 1843
	square_note 0, 1, 7, 1382
	square_note 0, 1, 6, 1625
	square_note 0, 2, 1, 1891
	square_note 0, 2, 1, 1785
	square_note 0, 2, 2, 1741
	square_note 0, 2, 2, 1613
	square_note 0, 2, 2, 1680
	square_note 0, 2, 2, 1769
	square_note 0, 2, 6, 1708
	square_note 0, 2, 1, 1885
	square_note 0, 2, 3, 1774
	square_note 0, 2, 6, 1741
	square_note 0, 3, 6, 1478
	square_note 0, 3, 7, 1422
	square_note 0, 3, 2, 1680
	square_note 0, 3, 2, 1769
	square_note 0, 3, 7, 1069
	square_note 1, 0, 0, 0
	sound_ret

Cry_Wartortle_Siren_Ch8:
	noise_note 0, 0, 8, 0
	noise_note 1, 8, 8, 92
	noise_note 1, 10, 8, 92
	noise_note 3, 8, 8, 92
	noise_note 0, 10, 8, 92
	noise_note 21, 8, 8, 92
	noise_note 0, 10, 8, 92
	noise_note 0, 8, 8, 92
	noise_note 0, 5, 8, 92
	noise_note 0, 8, 8, 92
	noise_note 0, 5, 8, 92
	noise_note 1, 8, 8, 92
	noise_note 1, 5, 8, 92
	noise_note 17, 0, 8, 0
	sound_ret
