; Generated by Siren
; Source: ampharos.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Custom_Ampharos:
	channel_count 3
	channel 5, Cry_Custom_Ampharos_Ch5
	channel 6, Cry_Custom_Ampharos_Ch6
	channel 8, Cry_Custom_Ampharos_Ch8

Cry_Custom_Ampharos_Ch5:
	duty_cycle 2
	square_note 1, 13, 8, 1620
	duty_cycle 0
	square_note 1, 13, 8, 1653
	square_note 1, 13, 8, 1258
	duty_cycle 1
	square_note 1, 13, 8, 1336
	square_note 1, 13, 8, 1303
	duty_cycle 2
	square_note 1, 13, 8, 1692
	square_note 1, 13, 8, 1678
	duty_cycle 0
	square_note 1, 13, 8, 878
	square_note 1, 13, 8, 1573
	duty_cycle 2
	square_note 1, 13, 8, 1602
	duty_cycle 1
	square_note 1, 13, 8, 1502
	square_note 1, 13, 8, 1511
	duty_cycle 2
	square_note 1, 13, 8, 1084
	square_note 1, 13, 8, 1559
	duty_cycle 1
	square_note 1, 13, 8, 1710
	square_note 1, 13, 8, 711
	square_note 1, 13, 8, 1418
	duty_cycle 2
	square_note 1, 13, 8, 1699
	duty_cycle 1
	square_note 1, 13, 8, 1715
	duty_cycle 0
	square_note 1, 13, 8, 0
	duty_cycle 2
	square_note 1, 13, 8, 0
	square_note 1, 13, 8, 0
	square_note 1, 11, 8, 0
	duty_cycle 1
	square_note 1, 6, 8, 1418
	duty_cycle 0
	square_note 1, 3, 8, 1399
	duty_cycle 2
	square_note 1, 0, 8, 0
	duty_cycle 1
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 0, 8, 0
	sound_ret

Cry_Custom_Ampharos_Ch6:
	duty_cycle 2
	square_note 1, 6, 8, 1577
	duty_cycle 3
	square_note 1, 7, 8, 1386
	duty_cycle 2
	square_note 1, 5, 8, 1684
	duty_cycle 3
	square_note 1, 5, 8, 1816
	duty_cycle 2
	square_note 1, 5, 8, 1818
	duty_cycle 3
	square_note 1, 5, 8, 1820
	duty_cycle 1
	square_note 1, 5, 8, 1800
	square_note 1, 5, 8, 1832
	duty_cycle 3
	square_note 1, 6, 8, 1822
	duty_cycle 2
	square_note 1, 6, 8, 1781
	duty_cycle 3
	square_note 1, 0, 8, 0
	duty_cycle 0
	square_note 1, 6, 8, 1751
	duty_cycle 2
	square_note 1, 5, 8, 1778
	duty_cycle 3
	square_note 1, 7, 8, 1728
	duty_cycle 0
	square_note 1, 5, 8, 1729
	duty_cycle 1
	square_note 1, 8, 8, 1730
	duty_cycle 3
	square_note 1, 5, 8, 1835
	duty_cycle 1
	square_note 1, 5, 8, 1837
	square_note 1, 5, 8, 1824
	square_note 1, 6, 8, 1828
	duty_cycle 3
	square_note 1, 5, 8, 1836
	duty_cycle 2
	square_note 1, 5, 8, 1705
	duty_cycle 3
	square_note 1, 5, 8, 1708
	duty_cycle 1
	square_note 1, 0, 8, 0
	duty_cycle 3
	square_note 1, 2, 8, 1699
	duty_cycle 2
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	duty_cycle 3
	square_note 1, 0, 8, 0
	sound_ret

Cry_Custom_Ampharos_Ch8:
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 3, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 4, 8, 92
	noise_note 1, 3, 8, 92
	noise_note 1, 2, 8, 92
	noise_note 1, 2, 8, 92
	noise_note 1, 1, 8, 92
	noise_note 1, 0, 8, 92
	noise_note 1, 0, 8, 92
	noise_note 1, 0, 8, 92
	sound_ret
