; Generated by Siren
; Source: scizor.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Custom_Scizor:
	channel_count 3
	channel 5, Cry_Custom_Scizor_Ch5
	channel 6, Cry_Custom_Scizor_Ch6
	channel 8, Cry_Custom_Scizor_Ch8

Cry_Custom_Scizor_Ch5:
	duty_cycle 1
	square_note 1, 13, 8, 1483
	square_note 1, 13, 8, 1548
	square_note 1, 13, 8, 1570
	duty_cycle 0
	square_note 1, 13, 8, 1789
	duty_cycle 2
	square_note 1, 13, 8, 1258
	square_note 1, 13, 8, 1112
	square_note 1, 13, 8, 1405
	square_note 1, 13, 8, 1286
	duty_cycle 1
	square_note 1, 13, 8, 1826
	square_note 1, 13, 8, 1372
	duty_cycle 2
	square_note 1, 13, 8, 1218
	duty_cycle 1
	square_note 1, 13, 8, 1819
	duty_cycle 0
	square_note 1, 13, 8, 1536
	square_note 1, 13, 8, 1885
	duty_cycle 2
	square_note 1, 13, 8, 1888
	square_note 1, 13, 8, 1887
	duty_cycle 3
	square_note 1, 13, 8, 1891
	duty_cycle 1
	square_note 1, 13, 8, 1892
	duty_cycle 2
	square_note 1, 13, 8, 1239
	square_note 1, 13, 8, 1249
	square_note 1, 13, 8, 1162
	square_note 1, 13, 8, 1286
	square_note 1, 13, 8, 1197
	square_note 1, 13, 8, 1837
	square_note 1, 11, 8, 1249
	square_note 1, 10, 8, 1818
	square_note 1, 11, 8, 1835
	square_note 1, 10, 8, 1826
	square_note 1, 8, 8, 1811
	duty_cycle 1
	square_note 1, 6, 8, 1844
	duty_cycle 2
	square_note 1, 4, 8, 1800
	square_note 1, 2, 8, 1798
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_Scizor_Ch6:
	duty_cycle 2
	square_note 1, 9, 8, 1818
	square_note 1, 7, 8, 1784
	duty_cycle 0
	square_note 1, 7, 8, 1795
	square_note 1, 8, 8, 1824
	square_note 1, 6, 8, 1794
	square_note 1, 9, 8, 1788
	duty_cycle 2
	square_note 1, 5, 8, 1790
	duty_cycle 1
	square_note 1, 8, 8, 1830
	square_note 1, 8, 8, 1855
	duty_cycle 2
	square_note 1, 7, 8, 1816
	square_note 1, 9, 8, 1820
	square_note 1, 8, 8, 1924
	square_note 1, 9, 8, 1880
	duty_cycle 0
	square_note 1, 8, 8, 1823
	square_note 1, 6, 8, 1828
	duty_cycle 2
	square_note 1, 10, 8, 1830
	square_note 1, 9, 8, 1848
	square_note 1, 8, 8, 1876
	square_note 1, 9, 8, 1886
	duty_cycle 3
	square_note 1, 10, 8, 1844
	duty_cycle 2
	square_note 1, 8, 8, 1842
	square_note 1, 9, 8, 1835
	square_note 1, 9, 8, 1842
	square_note 1, 0, 8, 0
	duty_cycle 3
	square_note 1, 8, 8, 1842
	duty_cycle 2
	square_note 1, 5, 8, 1845
	square_note 1, 7, 8, 1814
	duty_cycle 0
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 5, 8, 1836
	square_note 1, 4, 8, 1813
	duty_cycle 0
	square_note 1, 3, 8, 1835
	square_note 1, 1, 8, 1834
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_Scizor_Ch8:
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 1, 1, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 0, 0, 8, 75
	sound_ret
