; Generated by Siren
; Source: typhlosion.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Custom_Typhlosion:
	channel_count 3
	channel 5, Cry_Custom_Typhlosion_Ch5
	channel 6, Cry_Custom_Typhlosion_Ch6
	channel 8, Cry_Custom_Typhlosion_Ch8

Cry_Custom_Typhlosion_Ch5:
	duty_cycle 0
	square_note 0, 0, 8, 0
	square_note 0, 13, 8, 1832
	duty_cycle 1
	square_note 0, 13, 8, 1577
	duty_cycle 0
	square_note 0, 13, 8, 1831
	duty_cycle 1
	square_note 0, 13, 8, 450
	duty_cycle 0
	square_note 0, 13, 8, 62
	square_note 0, 13, 8, 228
	duty_cycle 2
	square_note 0, 13, 8, 1573
	square_note 0, 13, 8, 1040
	duty_cycle 1
	square_note 0, 13, 8, 711
	duty_cycle 0
	square_note 0, 13, 8, 524
	duty_cycle 2
	square_note 0, 13, 8, 1502
	duty_cycle 0
	square_note 0, 13, 8, 1150
	duty_cycle 2
	square_note 0, 13, 8, 410
	duty_cycle 1
	square_note 0, 13, 8, 559
	square_note 0, 13, 8, 120
	duty_cycle 2
	square_note 0, 13, 8, 1418
	square_note 0, 13, 8, 788
	duty_cycle 3
	square_note 0, 13, 8, 788
	duty_cycle 2
	square_note 0, 13, 8, 1866
	square_note 0, 13, 8, 450
	square_note 0, 13, 8, 1866
	duty_cycle 0
	square_note 0, 13, 8, 1684
	duty_cycle 3
	square_note 0, 13, 8, 1684
	duty_cycle 1
	square_note 0, 13, 8, 1682
	duty_cycle 3
	square_note 0, 13, 8, 1690
	duty_cycle 1
	square_note 0, 13, 8, 937
	square_note 0, 13, 8, 0
	square_note 0, 13, 8, 1686
	duty_cycle 3
	square_note 0, 13, 8, 450
	duty_cycle 2
	square_note 0, 13, 8, 878
	duty_cycle 0
	square_note 0, 13, 8, 937
	duty_cycle 2
	square_note 0, 13, 8, 737
	duty_cycle 1
	square_note 0, 13, 8, 898
	duty_cycle 2
	square_note 0, 13, 8, 277
	square_note 0, 13, 8, 0
	square_note 0, 13, 8, 1859
	square_note 0, 13, 8, 1857
	square_note 0, 13, 8, 1859
	duty_cycle 1
	square_note 0, 13, 8, 1667
	duty_cycle 2
	square_note 0, 13, 8, 1858
	square_note 0, 13, 8, 1856
	square_note 0, 13, 8, 1856
	square_note 0, 13, 8, 1858
	square_note 0, 13, 8, 737
	duty_cycle 1
	square_note 0, 13, 8, 834
	duty_cycle 3
	square_note 0, 13, 8, 1648
	square_note 0, 13, 8, 1249
	duty_cycle 1
	square_note 0, 13, 8, 1667
	duty_cycle 2
	square_note 0, 13, 8, 1855
	duty_cycle 3
	square_note 0, 13, 8, 1862
	duty_cycle 1
	square_note 0, 13, 8, 1671
	square_note 0, 13, 8, 1667
	duty_cycle 2
	square_note 0, 13, 8, 1856
	duty_cycle 1
	square_note 0, 13, 8, 1662
	duty_cycle 3
	square_note 0, 13, 8, 1669
	duty_cycle 2
	square_note 0, 13, 8, 228
	square_note 0, 13, 8, 277
	duty_cycle 0
	square_note 0, 13, 8, 0
	duty_cycle 1
	square_note 0, 13, 8, 1320
	square_note 0, 13, 8, 856
	duty_cycle 0
	square_note 0, 13, 8, 0
	square_note 0, 13, 8, 763
	duty_cycle 2
	square_note 0, 13, 8, 1651
	duty_cycle 0
	square_note 0, 13, 8, 856
	duty_cycle 2
	square_note 0, 13, 8, 1412
	duty_cycle 1
	square_note 0, 13, 8, 1641
	duty_cycle 2
	square_note 0, 13, 8, 120
	square_note 0, 13, 8, 592
	square_note 0, 13, 8, 1532
	square_note 0, 13, 8, 323
	square_note 0, 13, 8, 62
	duty_cycle 0
	square_note 0, 12, 8, 277
	square_note 0, 13, 8, 450
	duty_cycle 3
	square_note 0, 13, 8, 1320
	duty_cycle 0
	square_note 0, 13, 8, 956
	duty_cycle 2
	square_note 0, 12, 8, 1277
	square_note 0, 13, 8, 1436
	square_note 0, 13, 8, 323
	square_note 0, 13, 8, 0
	square_note 0, 13, 8, 592
	duty_cycle 1
	square_note 0, 13, 8, 1162
	duty_cycle 2
	square_note 0, 11, 8, 1112
	duty_cycle 1
	square_note 0, 13, 8, 1358
	square_note 0, 13, 8, 323
	duty_cycle 2
	square_note 0, 13, 8, 1098
	square_note 0, 13, 8, 524
	square_note 0, 13, 8, 1328
	duty_cycle 0
	square_note 0, 13, 8, 974
	duty_cycle 2
	square_note 0, 10, 8, 1277
	square_note 0, 12, 8, 1463
	duty_cycle 0
	square_note 0, 10, 8, 834
	duty_cycle 1
	square_note 0, 11, 8, 1351
	duty_cycle 2
	square_note 0, 11, 8, 654
	duty_cycle 0
	square_note 0, 11, 8, 1218
	duty_cycle 1
	square_note 0, 6, 8, 834
	duty_cycle 2
	square_note 0, 8, 8, 1372
	duty_cycle 0
	square_note 0, 10, 8, 228
	duty_cycle 2
	square_note 0, 7, 8, 1070
	square_note 0, 6, 8, 1753
	square_note 0, 4, 8, 1577
	square_note 0, 3, 8, 1636
	square_note 0, 1, 8, 323
	square_note 0, 2, 8, 0
	duty_cycle 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 0, 8, 0
	duty_cycle 1
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	duty_cycle 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_Typhlosion_Ch6:
	duty_cycle 0
	square_note 0, 0, 8, 0
	duty_cycle 1
	square_note 0, 5, 8, 1680
	duty_cycle 3
	square_note 0, 5, 8, 1686
	duty_cycle 2
	square_note 0, 6, 8, 1669
	duty_cycle 3
	square_note 0, 8, 8, 1577
	duty_cycle 2
	square_note 0, 8, 8, 1684
	square_note 0, 6, 8, 1577
	duty_cycle 3
	square_note 0, 8, 8, 1671
	duty_cycle 2
	square_note 0, 6, 8, 1605
	duty_cycle 0
	square_note 0, 5, 8, 1865
	square_note 0, 6, 8, 1865
	square_note 0, 5, 8, 1865
	square_note 0, 6, 8, 1865
	square_note 0, 5, 8, 1864
	duty_cycle 2
	square_note 0, 5, 8, 1866
	duty_cycle 0
	square_note 0, 5, 8, 1865
	square_note 0, 5, 8, 1865
	duty_cycle 2
	square_note 0, 5, 8, 1864
	duty_cycle 3
	square_note 0, 5, 8, 1864
	duty_cycle 0
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 6, 8, 1864
	duty_cycle 0
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 6, 8, 1858
	duty_cycle 0
	square_note 0, 5, 8, 1854
	duty_cycle 1
	square_note 0, 5, 8, 1857
	duty_cycle 3
	square_note 0, 7, 8, 1861
	duty_cycle 2
	square_note 0, 6, 8, 1867
	duty_cycle 0
	square_note 0, 5, 8, 1864
	duty_cycle 2
	square_note 0, 6, 8, 1859
	square_note 0, 6, 8, 1864
	square_note 0, 5, 8, 1867
	square_note 0, 6, 8, 1864
	duty_cycle 0
	square_note 0, 7, 8, 1863
	duty_cycle 2
	square_note 0, 7, 8, 1862
	square_note 0, 6, 8, 1861
	square_note 0, 8, 8, 1860
	duty_cycle 3
	square_note 0, 5, 8, 1921
	duty_cycle 0
	square_note 0, 5, 8, 1921
	duty_cycle 3
	square_note 0, 0, 8, 0
	duty_cycle 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	duty_cycle 3
	square_note 0, 0, 8, 0
	duty_cycle 0
	square_note 0, 5, 8, 1921
	duty_cycle 2
	square_note 0, 0, 8, 0
	square_note 0, 7, 8, 1856
	square_note 0, 5, 8, 1852
	square_note 0, 4, 8, 1857
	duty_cycle 1
	square_note 0, 6, 8, 1860
	duty_cycle 2
	square_note 0, 5, 8, 1849
	square_note 0, 0, 8, 0
	duty_cycle 3
	square_note 0, 5, 8, 1914
	duty_cycle 2
	square_note 0, 5, 8, 1852
	duty_cycle 3
	square_note 0, 4, 8, 1865
	duty_cycle 2
	square_note 0, 5, 8, 1699
	square_note 0, 5, 8, 1622
	square_note 0, 0, 8, 0
	duty_cycle 0
	square_note 0, 5, 8, 1497
	square_note 0, 0, 8, 0
	square_note 0, 6, 8, 1430
	duty_cycle 3
	square_note 0, 6, 8, 1418
	duty_cycle 0
	square_note 0, 5, 8, 1665
	duty_cycle 2
	square_note 0, 7, 8, 1631
	square_note 0, 8, 8, 1656
	duty_cycle 1
	square_note 0, 5, 8, 1611
	duty_cycle 2
	square_note 0, 6, 8, 1667
	square_note 0, 7, 8, 1694
	square_note 0, 6, 8, 1483
	square_note 0, 6, 8, 1611
	duty_cycle 0
	square_note 0, 5, 8, 1653
	duty_cycle 3
	square_note 0, 5, 8, 1712
	duty_cycle 2
	square_note 0, 5, 8, 1719
	duty_cycle 0
	square_note 0, 5, 8, 1771
	square_note 0, 5, 8, 1614
	duty_cycle 2
	square_note 0, 6, 8, 1493
	duty_cycle 0
	square_note 0, 6, 8, 1544
	duty_cycle 2
	square_note 0, 5, 8, 1559
	duty_cycle 1
	square_note 0, 6, 8, 1386
	duty_cycle 3
	square_note 0, 6, 8, 1506
	duty_cycle 1
	square_note 0, 7, 8, 1524
	duty_cycle 2
	square_note 0, 5, 8, 1614
	square_note 0, 5, 8, 1536
	square_note 0, 7, 8, 1303
	duty_cycle 0
	square_note 0, 4, 8, 1268
	duty_cycle 2
	square_note 0, 7, 8, 1239
	square_note 0, 5, 8, 1478
	duty_cycle 3
	square_note 0, 7, 8, 1430
	duty_cycle 2
	square_note 0, 7, 8, 1590
	square_note 0, 7, 8, 1577
	square_note 0, 5, 8, 1622
	duty_cycle 3
	square_note 0, 5, 8, 1386
	duty_cycle 2
	square_note 0, 5, 8, 1372
	square_note 0, 6, 8, 1511
	square_note 0, 4, 8, 1622
	duty_cycle 3
	square_note 0, 5, 8, 1555
	duty_cycle 2
	square_note 0, 5, 8, 1493
	duty_cycle 3
	square_note 0, 3, 8, 1351
	duty_cycle 0
	square_note 0, 4, 8, 1258
	duty_cycle 2
	square_note 0, 5, 8, 1458
	duty_cycle 3
	square_note 0, 3, 8, 1430
	duty_cycle 2
	square_note 0, 3, 8, 1580
	square_note 0, 2, 8, 1358
	square_note 0, 2, 8, 1468
	duty_cycle 1
	square_note 0, 1, 8, 834
	duty_cycle 2
	square_note 0, 1, 8, 623
	square_note 0, 0, 8, 0
	duty_cycle 3
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	duty_cycle 1
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_Typhlosion_Ch8:
	noise_note 0, 0, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 6, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 6, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 6, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 6, 8, 75
	noise_note 0, 6, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 6, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	sound_ret
