; Generated by Siren
; Source: tyranitar.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Custom_Tyranitar:
	channel_count 3
	channel 5, Cry_Custom_Tyranitar_Ch5
	channel 6, Cry_Custom_Tyranitar_Ch6
	channel 8, Cry_Custom_Tyranitar_Ch8

Cry_Custom_Tyranitar_Ch5:
	duty_cycle 3
	square_note 1, 10, 8, 1583
	duty_cycle 1
	square_note 1, 13, 8, 1573
	duty_cycle 0
	square_note 1, 13, 8, 1070
	duty_cycle 2
	square_note 1, 13, 8, 1312
	square_note 1, 13, 8, 1405
	duty_cycle 1
	square_note 1, 13, 8, 1024
	square_note 1, 13, 8, 1098
	duty_cycle 2
	square_note 1, 13, 8, 898
	duty_cycle 0
	square_note 1, 13, 8, 737
	duty_cycle 2
	square_note 1, 13, 8, 559
	duty_cycle 0
	square_note 1, 13, 8, 488
	duty_cycle 3
	square_note 1, 13, 8, 1497
	duty_cycle 1
	square_note 1, 13, 8, 1436
	duty_cycle 2
	square_note 1, 13, 8, 1430
	square_note 1, 13, 8, 1430
	duty_cycle 1
	square_note 1, 13, 8, 1430
	square_note 1, 13, 8, 1478
	duty_cycle 3
	square_note 1, 13, 8, 1493
	duty_cycle 0
	square_note 1, 13, 8, 1430
	square_note 1, 13, 8, 1447
	duty_cycle 2
	square_note 1, 13, 8, 1468
	duty_cycle 1
	square_note 1, 13, 8, 1470
	duty_cycle 2
	square_note 1, 13, 8, 1405
	square_note 1, 13, 8, 1405
	duty_cycle 0
	square_note 1, 13, 8, 1408
	duty_cycle 1
	square_note 1, 13, 8, 1412
	duty_cycle 3
	square_note 1, 13, 8, 1412
	square_note 1, 13, 8, 1412
	duty_cycle 0
	square_note 1, 13, 8, 1424
	duty_cycle 1
	square_note 1, 13, 8, 1399
	duty_cycle 2
	square_note 1, 13, 8, 1295
	square_note 1, 13, 8, 1186
	duty_cycle 1
	square_note 1, 13, 8, 811
	duty_cycle 2
	square_note 1, 13, 8, 1365
	duty_cycle 3
	square_note 1, 7, 8, 1368
	square_note 1, 2, 8, 1372
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	duty_cycle 3
	square_note 1, 0, 8, 0
	sound_ret

Cry_Custom_Tyranitar_Ch6:
	duty_cycle 2
	square_note 1, 4, 8, 1532
	duty_cycle 0
	square_note 1, 5, 8, 1295
	duty_cycle 2
	square_note 1, 5, 8, 1239
	duty_cycle 3
	square_note 1, 5, 8, 1617
	duty_cycle 0
	square_note 1, 6, 8, 1680
	square_note 1, 5, 8, 1636
	duty_cycle 3
	square_note 1, 6, 8, 1628
	duty_cycle 2
	square_note 1, 5, 8, 1599
	duty_cycle 3
	square_note 1, 6, 8, 1593
	duty_cycle 0
	square_note 1, 4, 8, 1831
	square_note 1, 6, 8, 1828
	square_note 1, 4, 8, 1835
	duty_cycle 2
	square_note 1, 4, 8, 1857
	duty_cycle 3
	square_note 1, 5, 8, 1768
	duty_cycle 2
	square_note 1, 6, 8, 1767
	duty_cycle 3
	square_note 1, 4, 8, 1862
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 4, 8, 1753
	duty_cycle 0
	square_note 1, 5, 8, 1506
	duty_cycle 2
	square_note 1, 6, 8, 1532
	duty_cycle 0
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 5, 8, 1488
	square_note 1, 0, 8, 0
	square_note 1, 6, 8, 1483
	duty_cycle 0
	square_note 1, 7, 8, 1511
	duty_cycle 2
	square_note 1, 0, 8, 0
	square_note 1, 6, 8, 1452
	square_note 1, 5, 8, 1055
	duty_cycle 3
	square_note 1, 4, 8, 1125
	duty_cycle 0
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 5, 8, 811
	duty_cycle 3
	square_note 1, 7, 8, 737
	duty_cycle 2
	square_note 1, 4, 8, 1336
	square_note 1, 6, 8, 1452
	square_note 1, 3, 8, 1295
	square_note 1, 1, 8, 1197
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	duty_cycle 1
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 0, 8, 0
	sound_ret

Cry_Custom_Tyranitar_Ch8:
	noise_note 1, 6, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 1, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	sound_ret
